version: '3.8'

services:
  postgres:
    image: 'postgres:13.0-alpine'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
